Shader pipeline upgrade
TheCBProject/CodeChickenLib pull request #379
Opened 2021-11-19 15:09 UTC by KitsuneAlex

* Fix selective reload listeners not testing for resource type.
* Add binary shaders (OpenGL 4.6 only).

2021-11-20 03:43 UTC, covers1624 requested changes
Few unnecessary changes.

Please also remove all final local/parameter definitions and run my formatter.

2021-11-20 03:43 UTC, covers1624 commented on src/main/java/codechicken/lib/render/shader/AssetShaderObject.java
> +        if(resourcePredicate.test(VanillaResourceType.SHADERS)) {
Selective Resource reloading is dead in Forge.

This can be reverted.

2021-11-20 03:43 UTC, covers1624 commented on src/main/java/codechicken/lib/render/shader/AbstractShaderObject.java
> +        final boolean hasInvalidId = shaderId == -1;
Unnecessary changes, was perfectly readable before.

2021-11-20 03:43 UTC, covers1624 commented on src/main/java/codechicken/lib/render/shader/BinaryShaderObject.java
> +        if(resourcePredicate.test(VanillaResourceType.SHADERS)) {
Selective resource reloading is dead.

2021-11-20 03:43 UTC, covers1624 commented on src/main/java/codechicken/lib/render/shader/ShaderProgram.java
> +        if(resourcePredicate.test(VanillaResourceType.SHADERS)) {
Once again, selective resource reloading is dead.

2021-11-20 03:43 UTC, covers1624 commented on src/main/java/codechicken/lib/render/shader/ShaderProgramBuilder.java
> +    private static abstract class AbstractShaderObjectBuilder<B extends AbstractShaderObjectBuilder<B>> {
Do we really need to split this into 3 classes, why cant `BinaryShaderObjectBuilder` just extend from `ShaderObjectBuilder` like we discussed?

2021-11-20 03:43 UTC, covers1624 commented on src/main/java/codechicken/lib/render/shader/BinaryShaderObject.java
> +            t.printStackTrace();
Don't do this. Push it to a Log4j logger with a description.

2021-11-20 03:43 UTC, covers1624 commented on src/main/java/codechicken/lib/render/shader/BinaryShaderObject.java
> +                try(final ByteArrayOutputStream ostream = new ByteArrayOutputStream()) {
ByteArrayOutputStream does not need a try-with-resources.

2021-11-20 13:48 UTC, merged

2021-11-21 21:23 UTC, KitsuneAlex commented
<3~